# Generated by Django 5.2 on 2026-01-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subreddit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del subreddit (ej: SomebodyMakeThis)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Si está activo para scraping"
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True,
                        help_text="Última vez que se sincronizó con Reddit",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de creación del registro"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Última actualización del registro"
                    ),
                ),
            ],
            options={
                "verbose_name": "Subreddit",
                "verbose_name_plural": "Subreddits",
                "ordering": ["name"],
            },
        ),
    ]
