# Generated by Django 5.2 on 2026-01-17 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subreddits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reddit_id",
                    models.CharField(
                        help_text="ID único del post en Reddit",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Título del post", max_length=300),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Contenido completo del post"
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        help_text="Autor del post en Reddit", max_length=100
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        default=0, help_text="Puntuación (upvotes) en Reddit"
                    ),
                ),
                (
                    "url",
                    models.URLField(help_text="URL del post en Reddit", max_length=500),
                ),
                (
                    "created_at_reddit",
                    models.DateTimeField(help_text="Fecha de creación en Reddit"),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Resumen de 1 línea del problema/idea"
                    ),
                ),
                (
                    "problem",
                    models.TextField(
                        blank=True, help_text="Problema identificado por la IA"
                    ),
                ),
                (
                    "mvp_idea",
                    models.TextField(
                        blank=True, help_text="Idea de MVP sugerida por la IA"
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        blank=True,
                        help_text="Público objetivo identificado",
                        max_length=200,
                    ),
                ),
                (
                    "potential_score",
                    models.IntegerField(
                        blank=True, help_text="Puntuación de potencial 1-10", null=True
                    ),
                ),
                (
                    "tags",
                    models.TextField(blank=True, help_text="Tags separados por comas"),
                ),
                (
                    "analyzed",
                    models.BooleanField(
                        default=False, help_text="Si ya fue analizado por la IA"
                    ),
                ),
                (
                    "analyzed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Cuándo fue analizado por la IA",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de importación a nuestra BD"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Última actualización del registro"
                    ),
                ),
                (
                    "subreddit",
                    models.ForeignKey(
                        help_text="Subreddit de origen",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="subreddits.subreddit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "ordering": ["-created_at_reddit"],
                "indexes": [
                    models.Index(
                        fields=["reddit_id"], name="posts_post_reddit__b2866a_idx"
                    ),
                    models.Index(
                        fields=["analyzed"], name="posts_post_analyze_38ea66_idx"
                    ),
                    models.Index(
                        fields=["-created_at_reddit"],
                        name="posts_post_created_690296_idx",
                    ),
                ],
            },
        ),
    ]
