# Generated by Django 5.2 on 2026-01-17 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("topics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="ID único del producto en Product Hunt",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Nombre del producto", max_length=300),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="Tagline del producto",
                        max_length=300,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Descripción completa del producto"
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        help_text="Maker principal del producto", max_length=100
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        default=0, help_text="Puntuación (votos) en Product Hunt"
                    ),
                ),
                (
                    "votes_count",
                    models.IntegerField(
                        default=0, help_text="Número de votos"
                    ),
                ),
                (
                    "comments_count",
                    models.IntegerField(
                        default=0, help_text="Número de comentarios"
                    ),
                ),
                (
                    "url",
                    models.URLField(help_text="URL del producto en Product Hunt", max_length=500),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="URL del sitio web del producto",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "created_at_source",
                    models.DateTimeField(help_text="Fecha de creación en Product Hunt"),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Resumen de 1 línea del problema/idea"
                    ),
                ),
                (
                    "problem",
                    models.TextField(
                        blank=True, help_text="Problema identificado por la IA"
                    ),
                ),
                (
                    "mvp_idea",
                    models.TextField(
                        blank=True, help_text="Idea de MVP sugerida por la IA"
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        blank=True,
                        help_text="Público objetivo identificado",
                        max_length=200,
                    ),
                ),
                (
                    "potential_score",
                    models.IntegerField(
                        blank=True, help_text="Puntuación de potencial 1-10", null=True
                    ),
                ),
                (
                    "tags",
                    models.TextField(blank=True, help_text="Tags separados por comas"),
                ),
                (
                    "analyzed",
                    models.BooleanField(
                        default=False, help_text="Si ya fue analizado por la IA"
                    ),
                ),
                (
                    "analyzed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Cuándo fue analizado por la IA",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Fecha de importación a nuestra BD"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Última actualización del registro"
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        help_text="Topic de origen",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="topics.topic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
                "ordering": ["-created_at_source"],
                "indexes": [
                    models.Index(
                        fields=["external_id"], name="posts_post_externa_a1b2c3_idx"
                    ),
                    models.Index(
                        fields=["analyzed"], name="posts_post_analyze_38ea66_idx"
                    ),
                    models.Index(
                        fields=["-created_at_source"],
                        name="posts_post_created_690296_idx",
                    ),
                ],
            },
        ),
    ]
