# Generated by Django 5.2 on 2026-01-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_favorite"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="post",
            new_name="posts_post_externa_b9d864_idx",
            old_name="posts_post_externa_a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="post",
            new_name="posts_post_created_c84755_idx",
            old_name="posts_post_created_690296_idx",
        ),
        migrations.AlterField(
            model_name="post",
            name="target_audience",
            field=models.TextField(
                blank=True, help_text="Público objetivo identificado"
            ),
        ),
    ]
