# Generated by Django 5.2 on 2026-01-25 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_rename_post_to_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at_source"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterField(
            model_name="favorite",
            name="product",
            field=models.ForeignKey(
                help_text="Producto marcado como favorito",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="posts.product",
            ),
        ),
        migrations.AlterModelTable(
            name="product",
            table="posts_post",
        ),
    ]
