# Generated by Django 5.2 on 2026-01-27 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_update_product_meta"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="Contenido de la nota")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Cuándo se creó la nota"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Última actualización de la nota"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Producto sobre el que se escribe la nota",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="posts.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuario dueño de la nota",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota de Producto",
                "verbose_name_plural": "Notas de Productos",
                "db_table": "posts_productnote",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "product"],
                        name="posts_produ_user_id_01f08b_idx",
                    )
                ],
                "unique_together": {("user", "product")},
            },
        ),
    ]
